#!/bin/bash

if(("$#" != 1))
then
	echo "Requires Command Name as Argument"
	exit 1
fi


COMMANDNAME=$1

 pushd /usr/local/bin
 touch $COMMANDNAME 
 echo '#!/bin/bash' > $COMMANDNAME
 chmod 755 $COMMANDNAME
 subl $COMMANDNAME
 popd


